DROP DATABASE IF EXISTS MVP;

CREATE DATABASE MVP;

CREATE TABLE msgs (
  message_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  to INT NOT NULL,
  from INT NOT NULL,
  text VARCHAR(255) NOT NULL,
  time VARCHAR(12) NOT NULL
);
